version: '3.4'

services:
  usermicroservice:
    image: ${DOCKER_REGISTRY-}usermicroservice
    ports:
        - 52800:80
    build:
      context: .
      dockerfile: UserMicroservice\Dockerfile
    depends_on:
        - mssql
    links:
        - mssql

  eventmicroservice:
    image: ${DOCKER_REGISTRY-}eventmicroservice
    ports:
        - 52801:80
    build:
      context: .
      dockerfile: EventMicroservice/Dockerfile

  mssql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Password123"
        ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PPassword123", "-Q", "select 1"]
      interval: 1s
      retries: 20
  redis-api:
    image: redis:latest