version: '3.4'

services:
  usermicroservice:
    image: ${DOCKER_REGISTRY-}usermicroservice
    ports:
        - 52800:80
    build:
      context: .
      dockerfile: UserMicroservice\Dockerfile

  eventmicroservice:
    image: ${DOCKER_REGISTRY-}eventmicroservice
    ports:
        - 52801:80
    build:
      context: .
      dockerfile: EventMicroservice/Dockerfile

  mssql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Password123"
        ACCEPT_EULA: "Y"